### ISSUE TITLE
outstanding

### ISSUE THREAD

**Issue by einariii** [einariii/beamscene#67]
- [x] registration/login
- [x] about template 
- [x] comment out inactive menu links
- [x] post link accessibility
- [x] index layout
- [x] posts layout (remove content td, visible td)
- [ ] long-form post layout
- [x] implement ui breakpoints
- [ ] drop the seed database + add dummy content
- [ ] add comments/tags (all three of us)
- [ ] webring links + template (bonus)
- [x] decide on default sizing
- [ ] user settings menu placement
- [x] background color of comment box

**Comment by mvkvc** [comment]
QA review today:

- [ ] Sidebar moving positions
- [ ] Inner content not filling the full space (esp about)
- [ ] Inner content clipping into top bar
- [ ] Posts poor spacing hard to read
- [ ] Flash placement
- [ ] Codezone/webring comment out links
- [ ] Login showing to logged in user
- [ ] No logout button

**Comment by mvkvc** [comment]
Not ranked by prio but overall what I think we need, also the login and redirect to index worked for me just now.
